### ISSUE TITLE
pdmpk testing (LAPJV testing)

### ISSUE THREAD

**Issue by vatai** [vatai/mpk#35]
So the basic idea is very simple: try to make it work for everything possible!
Some of the problematic cases I've encountered (and comments/ideas how to solve them):
1. ~~`gen2mtx` not working properly (and/or `gen2` not generating proper matrices) for large sizes. If you follow the instructions in the documentation (which uses size = 4) it seems ok, but for size = 10 it fails. Solution:~~ write a totally new `mesh_gen` program which is a clone of `gen`/`gen2` but creates `.mtx` files directly. There is some code-written-in-hurry in `csr.{cc,h}` which sometimes reads val from the `mtx` file and sometimes uses the 1.0/num_of_neighbours "artificial" values used for (d)mpk. 
2. Addressed in #37: ~~There are different types of MTX files (see https://math.nist.gov/MatrixMarket/formats.html) So the header (the first line of the `mtx` file) tells you which kind of matrix it is. E.g. if it is `symmetric` then it lists only the values for `M[i,j]` but not for `M[j,i]`. `CSR` class should take care of that (again, I have some code, doing that but it was written in a hurry). There are also `real` and `pattern` matrices. `real` matrices have normal values, while `pattern` matrices don't have any values and they need to be filled (I guess again, the "artificial" values used for dmpk is the right choice here...  then CSR won't just read the matrices it will have to fill those values if it is a `pattern` matrix...  then `gen_mesh` should probably be able to make pattern matrices... we have to think this trough).~~ 
3. ~~Everything should be automated. So there has to be a couple of scripts which run everything. Care must be taken that they don't write over each others stuff. [SOLVED issue #36] So for example I should be able to download a bunch of tar.gz files which contain mtx files from https://sparse.tamu.edu/ and just run a script which executes pdmpk (and the tests) on all of them.~~

**Comment by vatai** [comment]
4. For some matrices downloaded from https://sparse.tamu.edu/ `pdmpk_prep` fails. I think it is ok to open an issue for each such matrix with the title: Matrix <matrixname> failing <programname> (I guess here <programname> could be one of `pdmpk_prep`, `pdmpk_exec` or `pdmpk_test`)

**Comment by utsavsinghal5** [comment]
[Mtx_test_reports.txt](https://github.com/vatai/mpk/files/3986425/Mtx_test_reports.txt)
Attaching errors recorded in testing on various matrices.

**Comment by vatai** [comment]
`Not a real matrix` is not a big issue. You should check the matrix, if it is complex or something else. If it is a complex matrix, I think we should ignore it for now. If it is a pattern matrix, we should make it work.

The other `Out of range` error is more serious. That needs investigation. It might be something to do with not being able to progress.

**Comment by vatai** [comment]
Basically there are to major issues left:
- Reading non-real non-general matrices (i.e. symmetric or pattern matrices). That issue can be discussed in issue #37 
- The LAPJV makes the program crash... can't explain why. Hence the rename of this issue to track that issue.

**Comment by vatai** [comment]
All the generated tests pass... This should be ok.
