### ISSUE TITLE
Make a separate method for phase processing loop in `comm_comp_patterns`

### ISSUE THREAD

**Issue by utsavsinghal5** [vatai/mpk#38]
For mirroring we have to call the phase processing loop many times. Due to this we have to repeatedly write this. It would be a better idea to make a separate method.

**Comment by vatai** [comment]
Actually, we had the wrong idea. The loop in `Buffers::Exec()` needs to be repeated. This is also important, but for a different reason: to be able to try different methods of "mirroring".
