### ISSUE TITLE
Make proper results to compare communications for various matrices.

### ISSUE THREAD

**Issue by utsavsinghal5** [vatai/mpk#40]
We have two types of mirroring, pdmpk and PA1, PA2 and so on. Make proper results documentation to observe the appropriate defects.

**Comment by vatai** [comment]
Could you clarify this?

**Comment by utsavsinghal5** [comment]
We have communication results for various implementations. We have mirroring(one or two types maybe) and  we have pdmpk. Now along with PA1, PA2, PA3 and so on, we need to make proper documentation of results. So that we can look for the matrices or look for the possible improvements based on the comparative communication results.

**Comment by vatai** [comment]
Added some scripts which might help with this: namely `get_stats.sh` and `org-tbls.py`
